---
# tasks file for roles/php-fpm
- name: Add repository for PHP 7.0
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Install the php packages
  apt: name={{ item }} state=present
  with_items: "{{ php_fpm_packages }}"

- name: Restart the apache2 service
  service: name=apache2 state=reloaded

